### ISSUE TITLE
config.plist是怎么配置的？

### ISSUE THREAD

**Issue by NietzscheX** [volca/asus-h110m-k-d3-hackintosh#1]
大佬你这个config是根据什么来配置的？
我是用的opencore0.6.3

h110m  + 8100的话，8100应该是coffe-lake

coffe-lake的官方文档是
https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#starting-point

那config.plist里的值基本上大都不一样，你是基于什么来填写的？

**Comment by volca** [comment]
这个config.plist是从另一个现成的H110m主板的配置复制过来的，我并没有做细致的调整。只能说是可以工作。

我之前也尝试了使用`OC gen-x`生成了coffe-lake对应的config.plist来驱动但是不能点亮
