### ISSUE TITLE
PciRoot Explanation 

### ISSUE THREAD

**Issue by MaydayAlaska** [volca/asus-h110m-k-d3-hackintosh#3]
Could you explain why you used PciRoot(0x0)/Pci(0x1F,0x3) instead of PciRoot(0x0)/Pci(0x1b,0x0) for the layout id? I'm trying to understand.
![Schermata 2021-05-12 alle 2 07 23 PM](https://user-images.githubusercontent.com/43659965/117972401-65558080-b32b-11eb-8d8a-52d813e1c253.png)

**Comment by volca** [comment]
I just copied the config from another worked H110m motherboard. I didn't check per config item but it works.
